### ISSUE TITLE
Scroll with scrubber

### ISSUE THREAD

**Issue by rsefer** [11hundred/scrollplay#1]
Page should scroll with the song

**Comment by 11hundred** [comment]
This could be a custom scroll bar. 
I was thinking it may be nice to animate a scroll bar pill in from the center right side of the screen and animate to top of the scroll position on play or initial page load. We could design it to look browser-y.

**Comment by 11hundred** [comment]
Woah. Cool, some finessing, not sure if it should be "fixed" to center, but
maybe more like a real scroll bar. very cool. We should throw some
scratching sounds for scroll action.

---

David Handschuh

www.11hundred.com
1249 West Devon Avenue
Chicago Il 60660

213-804-7600
