### ISSUE TITLE
Page Sharing

### ISSUE THREAD

**Issue by 11hundred** [11hundred/scrollplay#3]
Able to link to specific song / soundcloud file in URL for sharing

scollplay.github.io/artistname/song-name or some other convention

**Comment by rsefer** [comment]
Should read from URL (ex. /#138712349) and auto-load that track. URL should be updated on track change.

**Comment by 11hundred** [comment]
Very cool 

Thanks,
David 

---

David Handschuh
11hundred
1249 West Devon Avenue
Chicago, IL 60660

www.11hundred.com

**Comment by rsefer** [comment]
To do: needs to handle 'track ID not found'

**Comment by 11hundred** [comment]
Url not updating in WebKit. 

Thanks,
David 

---

David Handschuh
11hundred
1249 West Devon Avenue
Chicago, IL 60660

www.11hundred.com

**Comment by rsefer** [comment]
Still in a feature branch until I account for bad IDs. Will merge into master when possible

**Comment by 11hundred** [comment]
gatchha.

---

David Handschuh

www.11hundred.com
1249 West Devon Avenue
Chicago Il 60660

213-804-7600

**Comment by 11hundred** [comment]
Dope!

Thanks,
David 

---

David Handschuh
11hundred
1249 West Devon Avenue
Chicago, IL 60660

www.11hundred.com
